import type {
  AppState,
  BudgetCategory,
  HoneymoonDay,
  RunOfShowItem,
  SeatingTable,
  Vendor,
  WeekendEvent,
} from './types';

export const COLORS = [
  '#D4A0A0',
  '#7B6D5E',
  '#C9A96E',
  '#8FA68A',
  '#6B8E9B',
  '#A0856D',
  '#B5838D',
  '#9B8FB4',
  '#7EA8A0',
  '#C4956A',
  '#D4B5A0',
  '#A89B8C',
  '#8B9DAF',
  '#B8B0A0',
  '#C78283',
  '#6A9B8E',
  '#AB8FC4',
  '#9BAF8B',
  '#AF9B6B',
  '#8AAFB5',
];

export const DEFAULT_BUDGET_CATS: BudgetCategory[] = [
  { id: 'bc1', name: 'Paper & Signage', pct: 3 },
  { id: 'bc2', name: 'Venue & Ceremony', pct: 15 },
  { id: 'bc3', name: 'Food / Service', pct: 18 },
  { id: 'bc4', name: 'Beverage', pct: 10 },
  { id: 'bc5', name: 'Photos', pct: 10 },
  { id: 'bc6', name: 'Music / Entertainment', pct: 8 },
  { id: 'bc7', name: 'Florals / Decor', pct: 8 },
  { id: 'bc8', name: 'Rentals', pct: 8 },
  { id: 'bc9', name: 'Lodging / Transport', pct: 4 },
  { id: 'bc10', name: 'Vendors', pct: 4 },
  { id: 'bc11', name: 'Favors', pct: 1 },
  { id: 'bc12', name: 'Attire', pct: 6 },
  { id: 'bc13', name: 'Odds & Ends', pct: 2 },
  { id: 'bc14', name: 'Accidentals', pct: 3 },
];

export const DEFAULT_CHECKLIST: Record<string, string[]> = {
  '12 Months Out': [
    'Choose Wedding Motto / Theme',
    'Plan Engagement Party',
    'Establish Overall Budget',
    'First Pass at Guest List',
    'Choose Time of Year',
    'Choose Wedding Date',
    'Choose & Book Venue',
    'Choose & Book Caterer',
    'Book Photographer',
    'Book DJ / Band',
    'Book Videographer',
    'Research Florists',
    'Research Wedding Planners',
    'Start Registry Research',
  ],
  '9 Months Out': [
    'Buy Wedding Dress',
    'Schedule Dress Alterations',
    'Design & Send Save the Dates',
    'Book Officiant',
    'Schedule Hair & Makeup Trials',
    'Create Gift Registry',
    'Book Hotel Room Block',
    'Research Wedding Insurance',
    'Choose Wedding Party Attire',
    'Plan Rehearsal Dinner Venue',
  ],
  '6 Months Out': [
    'Schedule Quality Time Together',
    'Finalize Decor & Lighting Plans',
    'Begin Premarital Counseling',
    'Discuss Prenup if Applicable',
    'Make DIY Decor Plan',
    'Book Dance Lessons',
    'Suit / Tux Try-On & Order',
    'Final Tasting with Caterer',
    'Order Wedding Cake',
    'Book Transportation',
    'Plan Honeymoon & Book Flights',
    'Apply for Passports if Needed',
  ],
  '3 Months Out': [
    'Plan Food Options / Menu',
    'Plan Guest Takeaways / Favors',
    'Begin Drafting Vows',
    'Select Ceremony Readings',
    'Get Crafty — DIY Projects',
    'Confirm All Vendor Lists',
    'Send Wedding Invitations',
    'Order Wedding Programs',
    'Finalize Ceremony Music',
    'Finalize Reception Playlist',
    'Plan Bachelorette / Bachelor Party',
    'Get Marriage License',
  ],
  'Month Of': [
    'Pay All Vendors in Full',
    'Create Seating Chart',
    'Order & Write Escort Cards',
    'Final Venue Walkthrough',
    'Break in Wedding Shoes',
    'Chase Outstanding RSVPs',
    'Confirm All Vendor Timelines',
    'Prepare Day-Of Emergency Kit',
    'Write Thank You Speech Notes',
    'Final Dress Fitting',
    'Confirm Honeymoon Reservations',
    'Arrange Pet / House Sitter',
  ],
  'Week Of & Night Before': [
    'Nail Appointment',
    'Final Dress / Suit Fitting',
    'Pack Car with Decor & Supplies',
    'Practice Vows Aloud',
    'Write Love Notes to Each Other',
    'Watch a Silly Movie Together',
    'Lay Out Outfit for Tomorrow',
    'Charge All Devices',
    'Confirm Arrival Times with Vendors',
    'Rehearsal & Rehearsal Dinner',
    "Get a Good Night's Sleep",
    'Enjoy the Moment',
  ],
};

export const DEFAULT_RUN_OF_SHOW: RunOfShowItem[] = [
  { id: 'r1', time: '2:00 PM', event: 'Guest Arrival & Pre-Ceremony Cocktails', detail: 'Guests mingle, find seats' },
  { id: 'r2', time: '3:00 PM', event: 'Wedding Party & Family Arrival', detail: 'Final photos before ceremony' },
  { id: 'r3', time: '3:45 PM', event: 'Guests Seated', detail: 'Ushers guide guests' },
  { id: 'r4', time: '4:00 PM', event: 'Processional & Ceremony', detail: 'The main event' },
  { id: 'r5', time: '4:30 PM', event: 'Ceremony Concludes — Recessional', detail: 'Newlyweds exit!' },
  { id: 'r6', time: '4:45 PM', event: 'Cocktail Hour Begins', detail: 'Drinks, appetizers, lawn games' },
  { id: 'r7', time: '5:00 PM', event: 'Couple Photos (Golden Hour)', detail: 'Photographer captures magic' },
  { id: 'r8', time: '5:45 PM', event: 'Reception Doors Open', detail: 'Guests find their tables' },
  { id: 'r9', time: '6:00 PM', event: 'Grand Entrance & First Dance', detail: 'The newlyweds take the floor' },
  { id: 'r10', time: '6:15 PM', event: 'Welcome Toast & Dinner Served', detail: 'Best Man / Maid of Honor toasts' },
  { id: 'r11', time: '7:15 PM', event: 'Parent Dances', detail: 'Father-Daughter, Mother-Son' },
  { id: 'r12', time: '7:30 PM', event: 'Cake Cutting', detail: 'Sweet moment together' },
  { id: 'r13', time: '7:45 PM', event: 'Open Dance Floor — Party!', detail: 'DJ/Band kicks it up' },
  { id: 'r14', time: '9:30 PM', event: 'Bouquet Toss', detail: "Who's next?" },
  { id: 'r15', time: '10:00 PM', event: 'Last Call & Final Song', detail: 'One more dance' },
  { id: 'r16', time: '10:15 PM', event: 'Sparkler Send-Off / Exit', detail: 'Farewell to the newlyweds' },
  { id: 'r17', time: '10:30 PM', event: 'After Party', detail: "For those who aren't done celebrating" },
];

export const DEFAULT_WEEKEND: WeekendEvent[] = [
  { id: 'w1', day: 'Friday', event: 'Hotel Check-in', time: '3:00 PM', notes: 'Guest arrivals begin' },
  { id: 'w2', day: 'Friday', event: 'Rehearsal', time: '5:00 PM', notes: 'Wedding party only' },
  { id: 'w3', day: 'Friday', event: 'Rehearsal Dinner', time: '7:00 PM', notes: 'Wedding party + close family' },
  { id: 'w4', day: 'Saturday', event: 'Wedding Day!', time: 'See Run of Show', notes: 'The big day' },
  { id: 'w5', day: 'Sunday', event: 'Farewell Brunch', time: '10:00 AM', notes: 'All guests welcome' },
  { id: 'w6', day: 'Sunday', event: 'Hotel Check-out', time: '11:00 AM', notes: '' },
];

export const DEFAULT_VENDORS: Vendor[] = [
  { id: 'v1', type: 'Planner', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
  { id: 'v2', type: 'Venue', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
  { id: 'v3', type: 'Caterer', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
  { id: 'v4', type: 'Photographer', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
  { id: 'v5', type: 'Videographer', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
  { id: 'v6', type: 'Florist', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
  { id: 'v7', type: 'DJ / Band', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
  { id: 'v8', type: 'Hair & Makeup', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
  { id: 'v9', type: 'Officiant', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
  { id: 'v10', type: 'Baker / Cake', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
  { id: 'v11', type: 'Transportation', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
  { id: 'v12', type: 'Rentals', name: '', contact: '', phone: '', email: '', stage: 'Not Started', cost: '', notes: '' },
];

export const DEFAULT_SEATING: SeatingTable[] = [
  { id: 's0', name: 'Sweetheart Table', type: 'sweetheart', guests: [], capacity: 2 },
  { id: 's1', name: 'Table 1', type: 'regular', guests: [], capacity: 8 },
  { id: 's2', name: 'Table 2', type: 'regular', guests: [], capacity: 8 },
  { id: 's3', name: 'Table 3', type: 'regular', guests: [], capacity: 8 },
  { id: 's4', name: 'Table 4', type: 'regular', guests: [], capacity: 8 },
  { id: 's5', name: 'Table 5', type: 'regular', guests: [], capacity: 8 },
  { id: 's6', name: 'Table 6', type: 'regular', guests: [], capacity: 8 },
  { id: 's7', name: 'Kings Table 1', type: 'kings', guests: [], capacity: 12 },
  { id: 's8', name: 'Kings Table 2', type: 'kings', guests: [], capacity: 12 },
];

export const DEFAULT_REGISTRY: Record<string, string[]> = {
  'Kitchen Accessories': [
    'Cooking Utensils Set',
    'Mandoline Slicer',
    'Kitchen Scale',
    'Measuring Cups & Spoons',
    'Strainer Set',
    'Ice Cream Scoop',
    'Kitchen Shears',
    'Garlic Press',
    'Can Opener',
    'Microplane',
    'Box Grater',
    'Sheet Trays',
    'Culinary Torch',
    'Spice Jar Set',
    'Working Glasses',
    'Bar Tool Set',
    'Teapot',
    'Citrus Reamer',
    'Coffee Scoop',
    'French Press',
    'Dish Towels',
  ],
  'Kitchen Appliances': [
    'Immersion Blender',
    'Juicer',
    'KitchenAid Stand Mixer',
    'Waffle Maker',
    'Microwave',
    'Espresso Machine',
    'Toaster',
    'Coffee Maker',
    'Food Processor',
    'Electric Kettle',
  ],
  Bakeware: ['Pie Dish', 'Loaf Pan', 'Bakeware Set', 'Silpat Baking Mat'],
  Cookware: [
    'Mixing Bowl Set',
    'Cutting Board Set',
    'Pots & Pans Set',
    'Stock Pot',
    'Non-Stick Pan',
    'Glass Nesting Bowls',
    'Baking Sheets',
    'Square Griddle',
    'Dutch Oven',
    'Pyrex Set',
    'Wok',
    'Magnetic Trivet',
    'Knife Set',
  ],
  Dinnerware: ['Casual Everyday Plates', 'Stoneware Set', 'Soup & Salad Bowls'],
  Glassware: [
    'Coffee Mugs',
    'Espresso Cups',
    'Pint Glasses',
    'Champagne Flutes',
    'Highball Glasses',
    'Old Fashioned Glasses',
    'Red Wine Glasses',
    'Stemless Wine Glasses',
    'Martini Glasses',
  ],
  Serveware: [
    'Salad Bowl',
    'Ramekin Set',
    'Cake Stand',
    'Glass Meal Prep Set',
    'Pitcher',
    'Serving Platters',
    'Linen Napkins',
    'Napkin Holders',
    'Cake Cutter Set',
    'Holiday China',
  ],
  Storage: [
    'Dry Storage Containers',
    'Glassware Storage',
    'Bowls with Lids',
    'Knife Storage Block',
    'Coffee Storage Canister',
  ],
  'Home Decor': [
    'Vase Collection',
    'Candlestick Set',
    'Art Pieces',
    'Lamps',
    'Decorative Cutting Board',
    'Throw Blankets',
    'Coffee Table Books',
  ],
  'Home Fun': ['Board Games', 'Hammock', 'Yeti Cooler', 'Camping Chairs'],
  Furniture: ['Dining Room Chairs', 'Bar Cart', 'Dining Cabinet / Sideboard'],
  Bedroom: ['Pillow Set', 'Comforter / Duvet', 'Sheet Set', 'Bedframe', 'Closet Organization', 'Hatch Alarm Clock'],
  Bathroom: ['Towel Sets', 'Matching Robes', 'Bathroom Accessories Set'],
  'Experience Gifts': [
    'Airbnb Gift Card',
    'Honeyfund',
    'Framebridge',
    'Charitable Donation',
    'Blue Apron',
    'Ruggable Gift Card',
  ],
};

export const DEFAULT_HONEYMOON_DAYS: HoneymoonDay[] = [
  { id: 'h1', day: 1, title: 'Departure Day', desc: 'Fly out — adventure begins!' },
  { id: 'h2', day: 2, title: 'Arrival & Settle In', desc: 'Check into hotel, explore the area' },
  { id: 'h3', day: 3, title: 'Day 3', desc: 'Plan your activities' },
  { id: 'h4', day: 4, title: 'Day 4', desc: 'Plan your activities' },
  { id: 'h5', day: 5, title: 'Day 5', desc: 'Plan your activities' },
  { id: 'h6', day: 6, title: 'Travel Home', desc: 'Head back as newlyweds!' },
];

export const DEFAULT_STATE: AppState = {
  settings: {
    brideName: 'Drew',
    groomName: 'Steven',
    weddingDate: '2026-03-12',
    weddingTime: '16:00',
    venueName: '',
    theme: 'sage',
    currency: '$',
  },
  budgetTotal: 35000,
  budgetCats: DEFAULT_BUDGET_CATS,
  budgetSpent: {},
  guests: [],
  checklist: {},
  checklistItems: Object.fromEntries(
    Object.entries(DEFAULT_CHECKLIST).map(([phase, items]) => [
      phase,
      items.map((t, i) => ({ id: `${phase}_${i}`, text: t })),
    ])
  ),
  vendors: DEFAULT_VENDORS,
  seating: DEFAULT_SEATING,
  runOfShow: DEFAULT_RUN_OF_SHOW,
  weekend: DEFAULT_WEEKEND,
  registryCats: Object.fromEntries(
    Object.entries(DEFAULT_REGISTRY).map(([cat, items]) => [
      cat,
      items.map((t, i) => ({ id: `${cat}_${i}_${Math.random().toString(36).slice(2, 7)}`, text: t })),
    ])
  ),
  registryChecked: {},
  giftTracker: [],
  venues: [],
  honeymoonDays: DEFAULT_HONEYMOON_DAYS,
  notes: '',
  honeymoonNotes: '',
  packingList: '',
  honeymoonDestination: '',
  honeymoonBudget: 0,
};
